### PR TITLE
closes #116

### LINKED ISSUE #116: hpa in 1.26 k8s  is not mapped properly
### Scenario

* Chart https://github.com/codecentric/helm-charts/tree/master/charts/keycloakx version 2.1.1 was deployed to EKS cluster 1.24. In this chart version `HorizontalPodAutoscaler` was defined with `apiVersion: autoscaling/v2beta2` https://github.com/codecentric/helm-charts/blob/653a238737a8d8a665913d23503cdc44bfa8bcd2/charts/keycloakx/templates/hpa.yaml
* Cluster got upgraded to 1.26
* Trying to upgrade keycloak chart 2.1.1 -> 2.2.1 caused. This time `apiVersion` is `autoscaling/v2` https://github.com/codecentric/helm-charts/blob/edcf6b2b7d1ff601bd15b5ee89f05397ffdb0821/charts/keycloakx/templates/hpa.yaml
```
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "platform-identity-keycloakx" namespace: "test" from "": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta2"
ensure CRDs are installed first
helm.go:84: [debug] resource mapping not found for name: "RELEASE_NAME-keycloakx" namespace: "default" from "": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta2"
```
* `helm mapkubeapis RELEASE_NAME` produced 
```
2023/05/04 11:42:07 Release 'RELEASE_NAME' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2023/05/04 11:42:07 Get release 'RELEASE_NAME' latest version.
2023/05/04 11:42:09 Check release 'RELEASE_NAME' for deprecated or removed APIs...
2023/05/04 11:42:09 Finished checking release 'RELEASE_NAME' for deprecated or removed APIs.
2023/05/04 11:42:09 Release 'RELEASE_NAME' has no deprecated or removed APIs.
2023/05/04 11:42:09 Map of release 'RELEASE_NAME' deprecated or removed APIs to supported versions, completed successfully.

```
### Problem
Cannot upgrade or uninstall the chart: 

```
uninstall.go:117: [debug] uninstall: Failed to delete release: [unable to build kubernetes objects for delete: resource mapping not found for name: "RELEASE_NAME-keycloakx" namespace: "default" from "": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta2"

```

Helm manifest still has deprecated `apiVersion`: 

```
helm get manifest RELEASE_NAME
...
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: RELEASE_NAME-keycloakx
...
```

### PR DESCRIPTION
**Pull request by EvgeniGordeev**

### CODE REVIEW

**Comment by jpalpant** [comment]
Hi @EvgeniGordeev, I was tracking down a similar issue and found this plugin and your fix, which work perfectly for me. I see your PR has some CI failures, would you like to clean that up and fill out the description to get this merged, or should I jump in?

**Comment by EvgeniGordeev** [comment]
@jpalpant I'm not familiar with the project or go - it'll take me some time to get up to speed here - feel free to help. This config worked for me with a cloned repo locally though.

**Comment by robertsirc** [comment]
This change made it in with another PR.

**Comment by mattfarina** [comment]
Thanks for the PR. Multiple PRs came in for this same thing and another one was already merged. Closing this one.

**Pull request closed without merging**
