### PR TITLE
Allow removal of deprecated API manifests

### LINKED ISSUE #85: Allow removal of resources for APIs that do not exist anymore
I was experimenting with `helm-mapkubeapis` and noticed that it currently does not offer a way of removing resources. However, in the case of the PodSecurityPolicy API, there is no new version to apply. It would be useful to have logic to allow removals when applicable.

### PR DESCRIPTION
**Pull request by stormqueen1990**
#### Changes
* Allow the removal of deprecated API manifests that do not have a successor API (such as PodSecurityPolicies).
* Add tests for verifying the changes in behaviour.

Fixes #85

### CODE REVIEW

**Comment by clrxbl** [comment]
I seem to be getting this upon attempting to use this PR:

```
❯ helm mapkubeapis postgres-exporter -n monitoring
2023/01/04 16:28:43 Release 'postgres-exporter' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2023/01/04 16:28:43 Get release 'postgres-exporter' latest version.
2023/01/04 16:28:43 Check release 'postgres-exporter' for deprecated or removed APIs...
2023/01/04 16:28:43 Found 1 instances of deprecated or removed Kubernetes API:
"apiVersion: policy/v1beta1
kind: PodSecurityPolicy
"
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/helm/helm-mapkubeapis/pkg/common.ReplaceManifestData(0xc0007b8051?, {0xc000b6a000?, 0xc0007b8053?}, {0xc0007b8050, 0xc})
        /tmp/helm-mapkubeapis/pkg/common/common.go:122 +0x609
github.com/helm/helm-mapkubeapis/pkg/common.ReplaceManifestUnSupportedAPIs({0xc000b6a000, 0x2f44}, {0xc000398dc0, 0x48}, {{0x0?, 0x14?}, {0x0?, 0xc0001b84d0?}})
        /tmp/helm-mapkubeapis/pkg/common/common.go:70 +0x109
github.com/helm/helm-mapkubeapis/pkg/v3.MapReleaseWithUnSupportedAPIs({0x0, {{0x0, 0x0}, {0x0, 0x0}}, {0xc000398dc0, 0x48}, {0x7fff048997b3, 0x11}, {0x0, ...}})
        /tmp/helm-mapkubeapis/pkg/v3/release.go:48 +0x19a
main.Map({0x0, {0xc000398dc0, 0x48}, {0x7fff048997b3, 0x11}, {0x0, 0x0}}, {{0x0, 0x0}, {0x0, ...}})
        /tmp/helm-mapkubeapis/cmd/mapkubeapis/map.go:127 +0x218
main.runMap(0xc0003b3680?, {0xc0001dba80?, 0x1?, 0x1?})
        /tmp/helm-mapkubeapis/cmd/mapkubeapis/map.go:104 +0xe7
github.com/spf13/cobra.(*Command).execute(0xc0003b3680, {0xc000050050, 0x1, 0x1})
        /home/michael/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003b3680)
        /home/michael/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/michael/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /tmp/helm-mapkubeapis/cmd/mapkubeapis/map_kube_apis.go:26 +0x6a
Error: plugin "mapkubeapis" exited with error
```

**Comment by stormqueen1990** [comment]
I imagine this happened because there's no `---` at the beginning of the manifest.

**Comment by clrxbl** [comment]
Now it doesn't seem to detect the PSP in deprecated / removed APIs.

**Comment by mattfarina** [comment]
There seems to be a problem with CI. We will investigate it.

**Comment by macedogm** [comment]
@mattfarina not sure if this is related, but the CI passed in PR https://github.com/helm/helm-mapkubeapis/pull/87. Maybe the CircleCI tokens were rotated in the meantime due to https://circleci.com/blog/january-4-2023-security-alert/?

**Comment by hickeyma** [comment]
> not sure if this is related, but the CI passed in PR https://github.com/helm/helm-mapkubeapis/pull/87

@macedogm Fixed the issue in CircleCi.

**Review by hickeyma — CHANGES_REQUESTED** [review]
@stormqueen1990 Do you mind rebasing and fix the conflicts?

**Comment by stormqueen1990** [comment]
> @stormqueen1990 Do you mind rebasing and fix the conflicts?

Hi there, @hickeyma! Not a problem, will update the branch.

**Comment by stormqueen1990** [comment]
Superseded by #91.

**Pull request closed without merging**
