### PR TITLE
Add autoscaling/v2beta2 HPA to map

### PR DESCRIPTION
**Pull request by dli7319**
Ran into an issue trying to upgrade ingress-nginx and mapkubeapis helped after adding autoscaling/v2beta2 to the map.
It would be great to have this included in the OOTB map.

### CODE REVIEW

**Review by joaope — APPROVED** [review]

**Review by yevsw — APPROVED** [review]

**Comment by Davidsoff** [comment]
@hickeyma @mattfarina Would be nice to get this merged. Ran into this today aswell

**Comment by edify42** [comment]
Bump @hickeyma @rimusz ?

**Review by ja250535 — APPROVED** [review]

**Comment by jamaalscarlett** [comment]
bump

**Comment by mohsen0** [comment]
any chance to merge this?

**Comment by robertsirc** [comment]
This change made it in with another PR.

**Comment by mattfarina** [comment]
Multiple PRs came in that add this and a different one was already merged. Closing this one.

**Pull request closed without merging**
