### PR TITLE
feat: allow removal of resources when APIs cease existing in Kubernetes

### LINKED ISSUE #85: Allow removal of resources for APIs that do not exist anymore
I was experimenting with `helm-mapkubeapis` and noticed that it currently does not offer a way of removing resources. However, in the case of the PodSecurityPolicy API, there is no new version to apply. It would be useful to have logic to allow removals when applicable.

### PR DESCRIPTION
**Pull request by stormqueen1990**
### Changes
* Enable `helm-mapkubeapis` to remove manifests of APIs that got removed from Kubernetes in Helm releases.

Fixes #85

### CODE REVIEW

**Comment by mateuszdrab** [comment]
I think this will be critical to be included, as many users will find themselves upgrade their clusters and realize their HELM deployments (which deployed PSPs) are broken. As you know, nobody really does the prep-work prior to the upgrade 😉

**Comment by mugioka** [comment]
nice feature ❤️

**Comment by mustafinra** [comment]
Tried out yor PR for PSP after cluster upgrade. Looks to work on 4 different versions of helm.

**Comment by mattfarina** [comment]
Closing as https://github.com/helm/helm-mapkubeapis/pull/95 was merged and contains the commits from here (cherry-picked).

**Pull request closed without merging**
