### PR TITLE
fix(Map.yaml) : added new map for hpa apiversion autoscaling/v2beta2

### PR DESCRIPTION
**Pull request by ramdaspotale**
The current version of plugin does not update hpa release manifest when it contains apiVersion autoscaling/v2beta2, it only works for autoscaling/v2beta1. hence i added one more mapping

### CODE REVIEW

**Comment by ramdaspotale** [comment]
@hickeyma

**Comment by ramdaspotale** [comment]
sorry for pinging individually as this changes is pending since March...and are causing issues with plugin

**Comment by danespinoza94** [comment]
+1 on this

**Review by soony88 — APPROVED** [review]

**Comment by soony88** [comment]
Sending my approval of this PR as a bump,

Posting in case anybody isn't aware,
As a workaround, you can copy the `Map.yaml` in this repo (along with the added HPA mapping) and save it as a local file to reference when running the binary with the following flag.

```
--mapfile string           path to the API mapping file (default "config/Map.yaml")
```

It's such a simple change and would also really appreciate if this got merged sooner rather than later

**Comment by ramdaspotale** [comment]
Thanks @soony88 for the bump, also for sharing the workaround although already have build plugin with updated map file as workaround.

**Comment by multhamb** [comment]
Please merge asap. We really need this feature

**Review by multhamb — APPROVED** [review]

**Review by ic-ruben-burgue — APPROVED** [review]

**Review by multhamb — APPROVED** [review]
Already tested with success:

**Comment by manny-semc** [comment]
+1

**Review by robertsirc — COMMENTED** [review]
This is covered in another PR.

**Comment by mattfarina** [comment]
Thanks for the PR. Multiple PRs came in to address this and another one has already been merged. Closing this one.

**Pull request closed without merging**
